const words = [
  "Blanket",
  "Helicopter",
  "President",
  "Bright",
  "Hurricane",
  "Rainbow",
  "Bump",
  "Kite",
  "Rollercoaster",
  "Christmas",
  "Light",
  "Shadow",
  "Coffee",
  "Magic",
  "Shopping",
  "Cradle",
  "Makeup",
  "Shuffle",
  "Deer",
  "Marriage",
  "Slice",
  "Drool",
  "Mash",
  "Slip n slide",
  "Electric Slide",
  "Measure",
  "Smear",
  "Excitement",
  "Mirror",
  "Spider",
  "Fight Club",
  "Monster",
  "The Lion King",
  "Firefighter",
  "Motorcycle",
  "Trampoline",
  "Flashlight",
  "Nightmare",
  "Waterfall",
  "Garden",
  "Nosey",
  "Window",
  "Giraffe",
  "Overwhelmed",
  "Yoyo",
  "Heavy",
  "Pancakes",
];

module.exports = { words };
